version: '3.8'
services:
  httpd:
    image: php:8-apache
    build:
      context: ./build
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./www:/var/www
      - ./conf/vhosts:/etc/apache2/sites-enabled
      - ./logs/httpd:/var/log/apache2
